# Generated by Django 5.0.1 on 2024-04-28 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djclass_1', '0003_python'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='python',
            new_name='PythonModel',
        ),
    ]
