# Generated by Django 5.0.1 on 2024-04-28 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djclass_1', '0004_rename_python_pythonmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pythonmodel',
            old_name='content',
            new_name='content_p',
        ),
        migrations.RenameField(
            model_name='pythonmodel',
            old_name='created_at',
            new_name='created_at_p',
        ),
        migrations.RenameField(
            model_name='pythonmodel',
            old_name='photo',
            new_name='photo_p',
        ),
        migrations.RenameField(
            model_name='pythonmodel',
            old_name='title',
            new_name='title_p',
        ),
        migrations.RenameField(
            model_name='pythonmodel',
            old_name='video',
            new_name='video_p',
        ),
    ]
