# Generated by Django 5.0.1 on 2024-04-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djclass_1', '0006_webccc'),
    ]

    operations = [
        migrations.CreateModel(
            name='webgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_go', models.CharField(max_length=200)),
                ('content_c', models.TextField()),
                ('photo_go', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('video_go', models.ImageField(blank=True, null=True, upload_to='videos/')),
                ('created_at_go', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
