# Generated by Django 5.0.1 on 2024-04-29 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djclass_1', '0008_webjavascript'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webgo',
            old_name='content_c',
            new_name='content_go',
        ),
    ]
